# Generated by Django 5.1.15 on 2026-04-08 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checks', models.JSONField(help_text='Detailed results of each validation check. Format: [{"check": "tax_code_valid", "passed": true, "detail": "..."}]')),
                ('all_passed', models.BooleanField(db_index=True, help_text='Whether all checks passed successfully.')),
                ('failed_checks_count', models.PositiveIntegerField(default=0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_checks', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_checks', to='core.organisation')),
                ('work_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_checks', to='core.workrecord')),
            ],
            options={
                'db_table': 'compliance_check',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['work_record', '-checked_at'], name='compliance__work_re_455229_idx'), models.Index(fields=['all_passed'], name='compliance__all_pas_9383b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(db_index=True, help_text='Type of report (e.g., payroll_summary, cost_report, liability_report)', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('report_data', models.JSONField(help_text='The report content in structured format.')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='compliance/reports/%Y/%m/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_reports', to='core.organisation')),
            ],
            options={
                'db_table': 'compliance_report',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', '-generated_at'], name='compliance__report__602595_idx'), models.Index(fields=['organisation', '-generated_at'], name='compliance__organis_a1f8f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='RTISubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_type', models.CharField(choices=[('FPS', 'Full Payment Submission'), ('EPS', 'Employer Payment Summary')], db_index=True, max_length=10)),
                ('payload', models.JSONField(help_text='The RTI submission payload sent to HMRC.')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Response received from HMRC.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('tax_year', models.CharField(help_text='Tax year in format YYYY-YY (e.g., 2025-26)', max_length=7)),
                ('tax_period', models.PositiveIntegerField(help_text='Tax period number (1-12 for monthly)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rti_submissions', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rti_submissions', to='core.organisation')),
                ('work_record', models.ForeignKey(blank=True, help_text='Related work record (for FPS). Null for monthly EPS.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rti_submissions', to='core.workrecord')),
            ],
            options={
                'db_table': 'compliance_rti_submission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['submission_type', 'status'], name='compliance__submiss_c1de67_idx'), models.Index(fields=['organisation', '-created_at'], name='compliance__organis_8da952_idx'), models.Index(fields=['tax_year', 'tax_period'], name='compliance__tax_yea_341d84_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatutoryDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PAYSLIP', 'Payslip'), ('P45', 'P45 - Leaving Certificate'), ('P60', 'P60 - Annual Summary')], db_index=True, max_length=20)),
                ('file', models.FileField(help_text='Generated PDF document.', upload_to='compliance/documents/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes.')),
                ('financial_data', models.JSONField(default=dict, help_text='Snapshot of financial data at time of generation. Includes gross pay, deductions, net pay, tax code, etc.')),
                ('tax_year', models.CharField(max_length=7)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('retention_until', models.DateField(help_text='Document must be retained until this date (7-year minimum).')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statutory_documents', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statutory_documents', to='core.organisation')),
                ('work_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statutory_documents', to='core.workrecord')),
            ],
            options={
                'db_table': 'compliance_statutory_document',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['contractor', 'document_type'], name='compliance__contrac_184845_idx'), models.Index(fields=['document_type', '-generated_at'], name='compliance__documen_fb8d0c_idx'), models.Index(fields=['tax_year'], name='compliance__tax_yea_ce5976_idx'), models.Index(fields=['organisation', '-generated_at'], name='compliance__organis_f52bbe_idx')],
            },
        ),
    ]
