# Generated by Django 5.1.15 on 2026-04-01 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_role', models.CharField(blank=True, help_text='Role of the actor at the time of the action.', max_length=30)),
                ('event_type', models.CharField(choices=[('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('TIMESHEET_SUBMITTED', 'Timesheet Submitted'), ('TIMESHEET_APPROVED', 'Timesheet Approved'), ('TIMESHEET_REJECTED', 'Timesheet Rejected'), ('INVOICE_GENERATED', 'Invoice Generated'), ('INVOICE_APPROVED', 'Invoice Approved'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYROLL_STARTED', 'Payroll Started'), ('PAYROLL_COMPLETED', 'Payroll Completed'), ('PAYROLL_BLOCKED', 'Payroll Blocked'), ('COMPLIANCE_CHECK_PASSED', 'Compliance Check Passed'), ('COMPLIANCE_CHECK_FAILED', 'Compliance Check Failed'), ('RTI_SUBMISSION_SENT', 'RTI Submission Sent'), ('RTI_SUBMISSION_ACCEPTED', 'RTI Submission Accepted'), ('RTI_SUBMISSION_REJECTED', 'RTI Submission Rejected'), ('DOCUMENT_GENERATED', 'Document Generated'), ('EXCEPTION_RAISED', 'Exception Raised'), ('EXCEPTION_ASSIGNED', 'Exception Assigned'), ('EXCEPTION_ESCALATED', 'Exception Escalated'), ('EXCEPTION_RESOLVED', 'Exception Resolved'), ('MANUAL_OVERRIDE', 'Manual Override Applied'), ('NOTIFICATION_SENT', 'Notification Sent'), ('NOTIFICATION_FAILED', 'Notification Failed'), ('CONFIG_CHANGED', 'Configuration Changed')], db_index=True, help_text='Categorised event type.', max_length=50)),
                ('before_state', models.CharField(blank=True, help_text='State before the transition.', max_length=30)),
                ('after_state', models.CharField(blank=True, help_text='State after the transition.', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context: rejection reasons, amounts, IP addresses, override justifications, etc.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the request.')),
                ('request_id', models.CharField(blank=True, help_text='Unique request identifier for tracing.', max_length=64)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action. Null for system-initiated events.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, help_text='Organisation context of the action.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='core.organisation')),
                ('work_record', models.ForeignKey(blank=True, help_text='The Work Record this event relates to, if applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='core.workrecord')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['-timestamp'], name='audit_log_timesta_8b04a8_idx'), models.Index(fields=['event_type', '-timestamp'], name='audit_log_event_t_37db9c_idx'), models.Index(fields=['actor', '-timestamp'], name='audit_log_actor_i_485cf7_idx'), models.Index(fields=['work_record', '-timestamp'], name='audit_log_work_re_4034e6_idx'), models.Index(fields=['organisation', '-timestamp'], name='audit_log_organis_20f485_idx'), models.Index(fields=['request_id'], name='audit_log_request_a46c86_idx')],
            },
        ),
    ]
