# Generated by Django 5.1.15 on 2026-04-01 11:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('AGENCY_ADMIN', 'Agency Admin'), ('AGENCY_CONSULTANT', 'Agency Consultant'), ('UMBRELLA_ADMIN', 'Umbrella Admin'), ('PAYROLL_OPERATOR', 'Payroll Operator'), ('CONTRACTOR', 'Contractor')], db_index=True, default='CONTRACTOR', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'core_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('AGENCY', 'Agency'), ('UMBRELLA', 'Umbrella Company')], db_index=True, max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('paye_reference', models.CharField(blank=True, help_text='HMRC PAYE scheme reference (e.g., 123/AB45678)', max_length=20)),
                ('paye_scheme_active', models.BooleanField(default=True, help_text='Whether the PAYE scheme is currently active with HMRC')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_organisation',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['org_type'], name='core_organi_org_typ_65e4fa_idx'), models.Index(fields=['paye_reference'], name='core_organi_paye_re_951030_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('AGENCY_ADMIN', 'Agency Admin'), ('AGENCY_CONSULTANT', 'Agency Consultant'), ('UMBRELLA_ADMIN', 'Umbrella Admin'), ('PAYROLL_OPERATOR', 'Payroll Operator'), ('CONTRACTOR', 'Contractor')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organisation')),
            ],
            options={
                'db_table': 'core_membership',
            },
        ),
        migrations.CreateModel(
            name='ContractorLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Agreed hourly rate in GBP', max_digits=10)),
                ('tax_code', models.CharField(blank=True, help_text='HMRC PAYE tax code (e.g., 1257L)', max_length=10)),
                ('ni_number', models.CharField(blank=True, help_text='UK National Insurance number', max_length=9, validators=[django.core.validators.RegexValidator(message='Enter a valid UK National Insurance number (e.g., QQ123456C)', regex='^[A-CEGHJ-PR-TW-Z]{2}\\d{6}[A-D]$')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'CONTRACTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_link', to=settings.AUTH_USER_MODEL)),
                ('agency', models.ForeignKey(limit_choices_to={'org_type': 'AGENCY'}, on_delete=django.db.models.deletion.PROTECT, related_name='agency_contractors', to='core.organisation')),
                ('umbrella', models.ForeignKey(limit_choices_to={'org_type': 'UMBRELLA'}, on_delete=django.db.models.deletion.PROTECT, related_name='umbrella_contractors', to='core.organisation')),
            ],
            options={
                'db_table': 'core_contractor_link',
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('WORK_SUBMITTED', 'Work Submitted'), ('WORK_APPROVED', 'Work Approved'), ('WORK_REJECTED', 'Work Rejected'), ('INVOICE_GENERATED', 'Invoice Generated'), ('INVOICE_APPROVED', 'Invoice Approved'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYROLL_PROCESSING', 'Payroll Processing'), ('PAYROLL_COMPLETED', 'Payroll Completed'), ('COMPLIANCE_SUBMITTED', 'Compliance Submitted'), ('COMPLETED', 'Completed')], db_index=True, default='WORK_SUBMITTED', max_length=30)),
                ('period_start', models.DateField(help_text='Start of the work period')),
                ('period_end', models.DateField(help_text='End of the work period')),
                ('hours_worked', models.DecimalField(decimal_places=2, help_text='Total hours worked in this period', max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate at time of submission (snapshot)', max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Calculated gross amount (hours × rate)', max_digits=12)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic locking version — incremented on every state change')),
                ('is_locked', models.BooleanField(default=False, help_text='Locked after approval — no further edits permitted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(limit_choices_to={'org_type': 'AGENCY'}, on_delete=django.db.models.deletion.PROTECT, related_name='agency_work_records', to='core.organisation')),
                ('contractor', models.ForeignKey(limit_choices_to={'role': 'CONTRACTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='work_records', to=settings.AUTH_USER_MODEL)),
                ('umbrella', models.ForeignKey(limit_choices_to={'org_type': 'UMBRELLA'}, on_delete=django.db.models.deletion.PROTECT, related_name='umbrella_work_records', to='core.organisation')),
            ],
            options={
                'db_table': 'core_work_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='core_user_role_73872d_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'organisation'], name='core_member_user_id_ec57e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'organisation', 'role')},
        ),
        migrations.AddIndex(
            model_name='contractorlink',
            index=models.Index(fields=['agency'], name='core_contra_agency__91b6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorlink',
            index=models.Index(fields=['umbrella'], name='core_contra_umbrell_77707f_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorlink',
            index=models.Index(fields=['tax_code'], name='core_contra_tax_cod_95610a_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['state'], name='core_work_r_state_557e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['contractor', 'state'], name='core_work_r_contrac_f66cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['agency', 'state'], name='core_work_r_agency__92f8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['umbrella', 'state'], name='core_work_r_umbrell_204825_idx'),
        ),
        migrations.AddIndex(
            model_name='workrecord',
            index=models.Index(fields=['period_start', 'period_end'], name='core_work_r_period__d62723_idx'),
        ),
    ]
